[pytest]
filterwarnings =
    ignore:The 'alias' attribute with value .* was provided to the `Field\(\)` function.*:pydantic.warnings.UnsupportedFieldAttributeWarning
    ignore:The 'validation_alias' attribute with value .* was provided to the `Field\(\)` function.*:pydantic.warnings.UnsupportedFieldAttributeWarning
    ignore:The 'serialization_alias' attribute with value .* was provided to the `Field\(\)` function.*:pydantic.warnings.UnsupportedFieldAttributeWarning
